### ISSUE TITLE
Chatbot not working from the last HB update

### ISSUE THREAD

**Issue by Belzedar94** [Vayku/Hanbot#2]
Not working anymore from my side :(((

**Comment by Belzedar94** [comment]
Working today, seems like the issue was on the Cleverbot API or something

**Comment by Vayku** [comment]
Hey! 

The script makes the request through a proxy to freely communicate with cleverbot. This is however hosted on Heroku as a free app, which is restricted to 550 hours. This could lead to the last few days it cutting off.
